#### Aula 23 - Matrizes no NumPy

 Ex. 1: Implemente o exemplo das frutas no Python 
|       | Maçã | Pera | Laranja |
|-------|------|------|---------|
| João  | 6    | 3    | 10      |
| Maria | 4    | 8    | 5       |

|       | Quit A | Quit B |
|-------|------|------|
| Maçã  | $0.10    | $0.15    |
| Pera | $0.40    | $0.30    |
| Laranja | $0.10    | $0.20    |


In [14]:
import numpy as np

In [18]:
F = np.array([[6, 3, 10],
              [4, 8, 5]])

P = np.array([[.1, .15],
              [.4, .3],
              [.1, .2]])

print('Quantidade de Frutas F:')
print(F)
print()
print('Preços P:')
print(P)
print()
print('Custo total F@P:')
print(F@P)

Quantidade de Frutas F:
[[ 6  3 10]
 [ 4  8  5]]

Preços P:
[[0.1  0.15]
 [0.4  0.3 ]
 [0.1  0.2 ]]

Custo total F@P:
[[2.8 3.8]
 [4.1 4. ]]


Ex. 2: Matriz inversa (Hilbert Matrix)

In [ ]:
from numpy.linalg import inv
%precision 3

H = np.array([[1/(i + j - 1)
                for j in range(1, 6)]
                    for i in range(1, 6)])

print('H:')
print(H)
print()
print('inv(H)')
print(inv(H))
print()
print('H@inv(H):')
print(H@inv(H))
print()
print('inv(H)@H:')
print(inv(H)@H)
print()
print('inv(inv(H)):')
print(inv(inv(H)))

H:
[[1.    0.5   0.333 0.25  0.2  ]
 [0.5   0.333 0.25  0.2   0.167]
 [0.333 0.25  0.2   0.167 0.143]
 [0.25  0.2   0.167 0.143 0.125]
 [0.2   0.167 0.143 0.125 0.111]]

inv(H)
[[ 2.500e+01 -3.000e+02  1.050e+03 -1.400e+03  6.300e+02]
 [-3.000e+02  4.800e+03 -1.890e+04  2.688e+04 -1.260e+04]
 [ 1.050e+03 -1.890e+04  7.938e+04 -1.176e+05  5.670e+04]
 [-1.400e+03  2.688e+04 -1.176e+05  1.792e+05 -8.820e+04]
 [ 6.300e+02 -1.260e+04  5.670e+04 -8.820e+04  4.410e+04]]

H@inv(H):
[[ 1.000e+00  4.058e-13  1.357e-12  1.931e-12  1.258e-13]
 [ 1.312e-14  1.000e+00 -4.163e-12 -3.966e-13 -1.924e-12]
 [ 3.561e-14 -9.497e-14  1.000e+00 -1.899e-12 -4.796e-13]
 [-1.421e-14  0.000e+00 -9.095e-13  1.000e+00 -9.095e-13]
 [ 2.842e-14 -9.095e-13  0.000e+00  0.000e+00  1.000e+00]]

inv(H)@H:
[[ 1.000e+00 -1.560e-12 -1.219e-12 -9.948e-13 -8.265e-13]
 [ 8.591e-12  1.000e+00  4.582e-12  4.547e-12  3.311e-12]
 [-1.683e-11 -1.386e-11  1.000e+00 -1.273e-11 -8.636e-12]
 [ 1.212e-11  8.092e-12  7.975e-12  1.000e+00